### ISSUE TITLE
Docker Version Support and Image Building

### ISSUE THREAD

**Issue by sawyerbutton** [jordanful/Promptspot#2]
Hi @jordanful , Would it be possible to provide a Dockerfile for image building? This would greatly streamline the process of using and testing the system, thereby improving efficiency.

I appreciate your consideration of this request.

**Comment by jordanful** [comment]
@sawyerbutton you bet. PR [here](https://github.com/jordanful/Promptspot/pull/3).

Want to have a look and lmk?

**Comment by sawyerbutton** [comment]
> @sawyerbutton you bet. PR [here](https://github.com/jordanful/Promptspot/pull/3).
> 
> Want to have a look and lmk?

Sure, I will. Thanks for this feature.
